#spring:
#  application:
#    name: expensemate
#
#  datasource:
#    url: jdbc:postgresql://localhost:6963/expensemate_db?ssl=false
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect



#server:
#  port: 9090
#
spring:
  application:
    name: expensemate

  datasource:
    url: jdbc:h2:mem:expensemate_db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true