spring:
  application:
    name: expensemate

  datasource:
    url: jdbc:postgresql://localhost:6963/expensemate_db?ssl=false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect